# -*- coding: utf-8 -*-
"""Taller #1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwupP_GrroJjc-XMgCdQ8F6tQBb2Ooa7
"""

import pandas as pd
import numpy as np
from google.colab import files
archivos = files.upload()

nombre_archivo = list(archivos.keys())[0]

df = pd.read_csv(
    nombre_archivo,
    sep=";",
    decimal=","
)

df.head()

df.shape

df_original = df.copy()

df.columns = df.columns.str.strip()

nulos_por_columna = df.isnull().sum()

nulos_totales = df.isnull().sum().sum()

print("Valores nulos totales:", nulos_totales)

duplicados = df.duplicated().sum()

print("Registros duplicados:", duplicados)

columnas_numericas = df.columns.difference(
    ["Country", "Energy Type"]
)

for columna in columnas_numericas:
    df[columna] = pd.to_numeric(
        df[columna],
        errors="coerce"
    )

df.isnull().sum().sum()

df.shape

print("DATOS ORIGINALES")
print("Filas:", df_original.shape[0])
print("Columnas:", df_original.shape[1])

print("\nDATOS TRANSFORMADOS")
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

resumen_etl = pd.DataFrame({
    "Indicador": [
        "Registros iniciales",
        "Columnas iniciales",
        "Valores nulos",
        "Duplicados",
        "Registros finales",
        "Columnas finales"
    ],

    "Resultado": [
        df_original.shape[0],
        df_original.shape[1],
        df_original.isnull().sum().sum(),
        df_original.duplicated().sum(),
        df.shape[0],
        df.shape[1]
    ]
})

resumen_etl

df.to_csv(
    "Energy_Data_Transformado.csv",
    index=False,
    sep=";",
    decimal=","
)

files.download("Energy_Data_Transformado.csv")